// CRUD EndPoints

GET http://localhost:3000/teste/hello
###
GET http://localhost:3000/teste/
###
POST http://localhost:3000/api/usuario/
Content-Type: application/json
 
{
    "Nome": "Tiago Salviano",
    "NameTag": "@TiagoMS",
    "Email": "tiago@example.com",
    "Password": "tiagotiago",
    "ProfilePicture": "link-to-a-pic",
    "Biografy": "Maybe you just have some bird ideas",
    "Following": "isadora@example.com"
}


###
GET http://localhost:3000/api/usuario/1
###
GET http://localhost:3000/api/usuario
###
DELETE http://localhost:3000/api/usuario/2
###
PATCH  http://localhost:3000/api/usuario/2 
Content-Type: application/json

{
    "Nome": "Tiago Miranda Salviano",
    "NameTag": "@TiagoMirandaS"
}
###

// Auth Endpoints

POST http://localhost:3000/api/usuario/auth/reg
Content-Type: application/json

{
    "NameTag": "@TiagoMS",
    "Email": "tiago@example.com",
    "Password": "tiagotiago"
}
###

POST http://localhost:3000/api/usuario/auth/login
Content-Type: application/json

{
    "Email": "tiago@example.com",
    "Password": "tiagotiago"
}
###

GET http://localhost:3000/api/usuario/auth/logout/3
###


// LoggedIn User Enpoints

GET http://localhost:3000/api/usuario/loggedIn/3
###