// CRUD EndPoints

GET http://localhost:3000/teste/hello
###
GET http://localhost:3000/teste/
###
POST http://localhost:3000/api/usuario/
Content-Type: application/json
 
{
    "Nome": "Tiago Salviano",
    "NameTag": "@TiagoMS",
    "Email": "tiago@example.com",
    "Password": "tiagotiago",
    "ProfilePicture": "link-to-a-pic",
    "Biografy": "Maybe you just have some bird ideas",
    "Following": "isadora@example.com"
}


###
GET http://localhost:3000/api/usuario/3 
###
GET http://localhost:3000/api/usuario
###
DELETE http://localhost:3000/api/usuario/3
###
PATCH  http://localhost:3000/api/usuario/2 
Content-Type: application/json

{
    "Nome": "Tiago Miranda Salviano",
    "NameTag": "@TiagoMirandaS"
}
###

// Auth Endpoints

POST http://localhost:3000/api/usuario/auth/reg
Content-Type: application/json

{
    "NameTag": "@TiagoMS",
    "Email": "tiago@example.com",
    "Password": "tiagotiago"
}
###

POST http://localhost:3000/api/usuario/auth/login
Content-Type: application/json

{
    "Email": "laranja@example.com",
    "Password": "laranja"
}
###

GET http://localhost:3000/api/usuario/auth/logout/6
###


// LoggedIn User Enpoints

GET http://localhost:3000/api/usuario/loggedIn/3
###

// Edit Profile Endpoints

POST http://localhost:3000/api/usuario/editProfile/6
Content-Type: application/json

{
    "Nome": "Limoeiro",
    "NameTag": "@MeuLimao",
    "ProfilePicture": "limao.jpg",
    "Biografy": "Meu Limao Meu limoeiro meuy pe. Meu pe de maracanga",
    "DarkMode": true
}

###

// Quem Seguir Aside Component
GET  http://localhost:3000/api/usuario/QuemSeguir/3?queryString=limao

###
GET http://localhost:3000/api/usuario/profile-picture/5
###
GET http://localhost:3000/api/usuario/allreceitas
###